# Generated by Django 5.1 on 2024-12-28 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0002_userrank_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrank',
            name='score',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
