# Generated by Django 5.1 on 2024-12-28 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0004_userrank_rank_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrank',
            name='profil',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userrank',
            name='profil_url',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
