# Generated by Django 5.1 on 2024-12-27 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='photo',
        ),
    ]
